import type { HealthReport, DependencyHealth, Grade } from "@epitaph-dev/core";

const GRADE_EMOJI: Record<Grade, string> = {
  A: "🟢",
  B: "🟢",
  C: "🟡",
  D: "🟠",
  F: "🔴",
};

const TREND_ARROWS: Record<string, string> = {
  growing: "↑",
  stable: "→",
  declining: "↓",
};

function signalSummary(dep: DependencyHealth): string {
  return dep.signals.map((s) => `${s.emoji} ${s.value}`).join(" · ");
}

function formatDownloads(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`;
  return String(n);
}

function compactDetails(dep: DependencyHealth): string {
  const parts: string[] = [];

  if (dep.busFactor > 0) {
    parts.push(`👤 BF:${dep.busFactor}`);
  }

  if (dep.medianIssueResponseDays !== null) {
    parts.push(`⏱️ ${dep.medianIssueResponseDays}d`);
  }

  if (dep.weeklyDownloads > 0) {
    parts.push(`📥 ${formatDownloads(dep.weeklyDownloads)}${TREND_ARROWS[dep.downloadTrend] ?? ""}`);
  }

  if (dep.hasFunding) {
    parts.push("💰");
  }

  return parts.join(" ");
}

export function renderMarkdownReport(report: HealthReport): string {
  const lines: string[] = [];

  lines.push("## 🪦 epitaph — Dependency Health Report");
  lines.push("");

  const { total, dead, warning, caution, healthy } = report.summary;
  lines.push(
    `**${total}** scanned · **${dead}** dead · **${warning}** warning · **${caution}** caution · **${healthy}** healthy`,
  );
  lines.push("");

  const noteworthy = report.dependencies.filter(
    (d) => d.error === null && (d.grade === "F" || d.grade === "D" || d.grade === "C"),
  );

  if (noteworthy.length === 0) {
    lines.push("All dependencies look healthy! ✨");
    return lines.join("\n");
  }

  lines.push("| Grade | Package | Signals | Details |");
  lines.push("|:-----:|---------|---------|---------|");

  for (const dep of noteworthy) {
    const emoji = GRADE_EMOJI[dep.grade];
    const name = dep.repoUrl
      ? `[${dep.name}](${dep.repoUrl})`
      : dep.name;
    const details = compactDetails(dep);
    lines.push(`| ${emoji} **${dep.grade}** | ${name} | ${signalSummary(dep)} | ${details} |`);
  }

  lines.push("");
  lines.push(
    "<details><summary>Full report (all dependencies)</summary>",
  );
  lines.push("");
  lines.push("| Grade | Package | Signals | Details |");
  lines.push("|:-----:|---------|---------|---------|");

  for (const dep of report.dependencies) {
    if (dep.error) continue;
    const emoji = GRADE_EMOJI[dep.grade];
    const name = dep.repoUrl
      ? `[${dep.name}](${dep.repoUrl})`
      : dep.name;
    const devTag = dep.isDev ? " *(dev)*" : "";
    const details = compactDetails(dep);
    lines.push(
      `| ${emoji} **${dep.grade}** | ${name}${devTag} | ${signalSummary(dep)} | ${details} |`,
    );
  }

  lines.push("");
  lines.push("</details>");
  lines.push("");
  lines.push("---");
  lines.push("*Generated by [epitaph](https://github.com/epitaph-dev/epitaph)*");

  return lines.join("\n");
}
